In [1]:
import pandas as pd

In [2]:
df = pd.read_html('tables.html')

In [3]:
#df

In [4]:
type(df)

list

In [5]:
def city(a,b,c,d):
    
    b.drop('Year',axis=1,inplace=True)
    df = pd.concat([a,b,c,d],axis=0)
    df.set_index('Month',inplace=True)
    df = df.set_index(pd.Index(['Avg Temp Min(°C)', 'Avg Temp Max(°C)', 'Avg Temp Min(°F)', 'Avg Temp Max(°F)','Avg Prec.(mm)','Avg Prec.(in)','No. days of Prec','Avg Hours Sunlight','Sea Temp(°C)','Sea Temp(°F)']))
    return df

In [6]:
capetown = city(df[0],df[1],df[2],df[3])

In [7]:
capetown

,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
Avg Temp Min(°C),16.0,16.0,14.0,12.0,9.0,8.0,7.0,8.0,9.0,11.0,13.0,15.0
Avg Temp Max(°C),26.0,27.0,25.0,23.0,20.0,18.0,18.0,18.0,19.0,21.0,24.0,25.0
Avg Temp Min(°F),61.0,61.0,57.0,54.0,48.0,46.0,45.0,46.0,48.0,52.0,55.0,59.0
Avg Temp Max(°F),79.0,81.0,77.0,73.0,68.0,64.0,64.0,64.0,66.0,70.0,75.0,77.0
Avg Prec.(mm),12.0,8.0,17.0,45.0,85.0,80.0,85.0,70.0,45.0,30.0,17.0,11.0
Avg Prec.(in),0.5,0.3,0.7,1.8,3.3,3.1,3.3,2.8,1.8,1.2,0.7,0.4
No. days of Prec,2.0,2.0,3.0,6.0,9.0,9.0,10.0,10.0,7.0,5.0,3.0,2.0
Avg Hours Sunlight,11.0,11.0,9.0,8.0,7.0,6.0,6.0,7.0,8.0,9.0,10.0,11.0
Sea Temp(°C),19.0,19.0,18.0,17.0,17.0,16.0,15.0,15.0,15.0,16.0,17.0,18.0
Sea Temp(°F),66.0,66.0,64.0,63.0,63.0,61.0,59.0,59.0,59.0,61.0,63.0,64.0

In [8]:
portelizabeth = city(df[13],df[12],df[14],df[15])

In [9]:
portelizabeth

,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
Avg Temp Min(°C),18.0,19.0,17,15.0,12.0,10.0,10.0,11.0,12.0,13.0,15.0,17.0
Avg Temp Max(°C),24.0,24.0,23,22.0,21.0,20.0,18.0,18.0,18.0,20.0,21.0,23.0
Avg Temp Min(°F),64.0,66.0,63,59.0,54.0,50.0,50.0,52.0,54.0,55.0,59.0,63.0
Avg Temp Max(°F),75.0,75.0,73,72.0,70.0,68.0,64.0,64.0,64.0,68.0,70.0,73.0
Avg Prec.(mm),35.0,35.0,50,45.0,65.0,60.0,60.0,55.0,60.0,65.0,60.0,40.0
Avg Prec.(in),1.4,1.4,2,1.8,2.6,2.4,2.4,2.2,2.4,2.6,2.4,1.6
No. days of Prec,3.0,5.0,6,5.0,6.0,5.0,5.0,6.0,8.0,8.0,7.0,5.0
Avg Hours Sunlight,9.0,8.0,7,7.0,7.0,7.0,7.0,8.0,7.0,8.0,8.0,9.0
Sea Temp(°C),23.0,24.0,24,23.0,23.0,21.0,20.0,20.0,20.0,20.0,21.0,23.0
Sea Temp(°F),73.0,75.0,75,73.0,73.0,70.0,68.0,68.0,68.0,68.0,70.0,73.0

In [10]:
durban = city(df[17],df[16],df[18],df[19])

In [11]:
durban

,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
Avg Temp Min(°C),21.0,21.0,20.0,17.0,14.0,11.0,11,13.0,15.0,17.0,18.0,20.0
Avg Temp Max(°C),28.0,28.0,28.0,26.0,25.0,23.0,23,23.0,23.0,24.0,25.0,27.0
Avg Temp Min(°F),70.0,70.0,68.0,63.0,57.0,52.0,52,55.0,59.0,63.0,64.0,68.0
Avg Temp Max(°F),82.0,82.0,82.0,79.0,77.0,73.0,73,73.0,73.0,75.0,77.0,81.0
Avg Prec.(mm),120.0,130.0,115.0,90.0,60.0,35.0,25,40.0,65.0,85.0,120.0,125.0
Avg Prec.(in),4.7,5.1,4.5,3.5,2.4,1.4,1,1.6,2.6,3.3,4.7,4.9
No. days of Prec,11.0,9.0,9.0,7.0,4.0,3.0,3,4.0,6.0,10.0,11.0,12.0
Avg Hours Sunlight,6.0,6.0,7.0,7.0,7.0,8.0,7,7.0,6.0,5.0,6.0,6.0
Sea Temp(°C),26.0,26.0,26.0,25.0,24.0,23.0,22,22.0,22.0,22.0,24.0,25.0
Sea Temp(°F),79.0,79.0,79.0,77.0,75.0,73.0,72,72.0,72.0,72.0,75.0,77.0

In [12]:
#correlation plot for capetown
cp= capetown.transpose().corr()
cp.corr()

,Avg Temp Min(°C),Avg Temp Max(°C),Avg Temp Min(°F),Avg Temp Max(°F),Avg Prec.(mm),Avg Prec.(in),No. days of Prec,Avg Hours Sunlight,Sea Temp(°C),Sea Temp(°F)
Avg Temp Min(°C),1.000000,0.999859,0.999999,0.999873,-0.997403,-0.997595,-0.999453,0.998407,0.996200,0.995233
Avg Temp Max(°C),0.999859,1.000000,0.999871,0.999999,-0.996277,-0.996502,-0.998856,0.997403,0.997247,0.996430
Avg Temp Min(°F),0.999999,0.999871,1.000000,0.999882,-0.997385,-0.997577,-0.999442,0.998373,0.996216,0.995250
Avg Temp Max(°F),0.999873,0.999999,0.999882,1.000000,-0.996305,-0.996531,-0.998879,0.997453,0.997245,0.996427
Avg Prec.(mm),-0.997403,-0.996277,-0.997385,-0.996305,1.000000,0.999996,0.999217,-0.999666,-0.987343,-0.985636
Avg Prec.(in),-0.997595,-0.996502,-0.997577,-0.996531,0.999996,1.000000,0.999323,-0.999725,-0.987772,-0.986093
No. days of Prec,-0.999453,-0.998856,-0.999442,-0.998879,0.999217,0.999323,1.000000,-0.999663,-0.992810,-0.991513
Avg Hours Sunlight,0.998407,0.997403,0.998373,0.997453,-0.999666,-0.999725,-0.999663,1.000000,0.989993,0.988493
Sea Temp(°C),0.996200,0.997247,0.996216,0.997245,-0.987343,-0.987772,-0.992810,0.989993,1.000000,0.999940
Sea Temp(°F),0.995233,0.996430,0.995250,0.996427,-0.985636,-0.986093,-0.991513,0.988493,0.999940,1.000000

In [13]:
#correlation plot for port elizbeth
#correlation plot for capetown
pe= portelizabeth.transpose().corr()
pe.corr()

,Avg Temp Min(°C),Avg Temp Max(°C),Avg Temp Min(°F),Avg Temp Max(°F),Avg Prec.(mm),Avg Prec.(in),No. days of Prec,Avg Hours Sunlight,Sea Temp(°C),Sea Temp(°F)
Avg Temp Min(°C),1.000000,0.990006,0.999943,0.988428,-0.994812,-0.994812,-0.933744,0.859631,0.961559,0.960328
Avg Temp Max(°C),0.990006,1.000000,0.990382,0.999917,-0.990445,-0.990445,-0.965205,0.814813,0.986718,0.985806
Avg Temp Min(°F),0.999943,0.990382,1.000000,0.988867,-0.994287,-0.994287,-0.933056,0.854798,0.963482,0.962304
Avg Temp Max(°F),0.988428,0.999917,0.988867,1.000000,-0.988635,-0.988635,-0.965364,0.808369,0.988213,0.987373
Avg Prec.(mm),-0.994812,-0.990445,-0.994287,-0.988635,1.000000,1.000000,0.959686,-0.881722,-0.958556,-0.956760
Avg Prec.(in),-0.994812,-0.990445,-0.994287,-0.988635,1.000000,1.000000,0.959686,-0.881722,-0.958556,-0.956760
No. days of Prec,-0.933744,-0.965205,-0.933056,-0.965364,0.959686,0.959686,1.000000,-0.812030,-0.950160,-0.948228
Avg Hours Sunlight,0.859631,0.814813,0.854798,0.808369,-0.881722,-0.881722,-0.812030,1.000000,0.713222,0.708718
Sea Temp(°C),0.961559,0.986718,0.963482,0.988213,-0.958556,-0.958556,-0.950160,0.713222,1.000000,0.999971
Sea Temp(°F),0.960328,0.985806,0.962304,0.987373,-0.956760,-0.956760,-0.948228,0.708718,0.999971,1.000000

In [14]:
#correlation plot for durban
db= durban.transpose().corr()
db.corr()

,Avg Temp Min(°C),Avg Temp Max(°C),Avg Temp Min(°F),Avg Temp Max(°F),Avg Prec.(mm),Avg Prec.(in),No. days of Prec,Avg Hours Sunlight,Sea Temp(°C),Sea Temp(°F)
Avg Temp Min(°C),1.000000,0.950478,0.999990,0.955000,0.998909,0.998933,0.979978,-0.925893,0.864655,0.884337
Avg Temp Max(°C),0.950478,1.000000,0.951498,0.999847,0.940151,0.940601,0.871208,-0.763377,0.977173,0.985262
Avg Temp Min(°F),0.999990,0.951498,1.000000,0.955960,0.998713,0.998739,0.979319,-0.924734,0.866181,0.885797
Avg Temp Max(°F),0.955000,0.999847,0.955960,1.000000,0.945347,0.945776,0.878771,-0.772900,0.974103,0.982632
Avg Prec.(mm),0.998909,0.940151,0.998713,0.945347,1.000000,0.999998,0.985507,-0.935063,0.850340,0.870297
Avg Prec.(in),0.998933,0.940601,0.998739,0.945776,0.999998,1.000000,0.985231,-0.934528,0.851089,0.870990
No. days of Prec,0.979978,0.871208,0.979319,0.878771,0.985507,0.985231,1.000000,-0.980521,0.750644,0.776103
Avg Hours Sunlight,-0.925893,-0.763377,-0.924734,-0.772900,-0.935063,-0.934528,-0.980521,1.000000,-0.610905,-0.642583
Sea Temp(°C),0.864655,0.977173,0.866181,0.974103,0.850340,0.851089,0.750644,-0.610905,1.000000,0.999014
Sea Temp(°F),0.884337,0.985262,0.885797,0.982632,0.870297,0.870990,0.776103,-0.642583,0.999014,1.000000